class TestData:
    url="http://164.52.223.30:8001/create-tenant/"
    url1="https://d25o0givni0pe6.cloudfront.net/"

    brandlogo1 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\Logo.svg"
    brandlogo2 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\Logo1.svg"
    brandlogo3 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\logo2.eps"
    feviconlogo1 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\fevlogo.ico"
    feviconlogo2 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\fevlogo1.ico"
    pageimage = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\landingImage.png"
    headline = "Enhance Your Business"
    subheadline = "with the largest inventory of digital hoardings in India"
    clientlogo1 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\Logo.svg"
    clientlogo2 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\Logo1.svg"
    clientlogo3 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\logo2.eps"
    clienticon1 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\man.PNG"
    clienticon2 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\man.PNG"
    clienticon3 = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\man.PNG"
    clientname1 = "Manoj"
    clientdesignation1 = "CEO of Facebook"
    clientcompany1 = "facbook"
    clienttext1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cursus nibh mauris, nec turpis orci lectus maecenas. Suspendisse sed magna eget nibh in turpis. Consequat duis diam lacus arcu. Faucibus venenatis felis id augue sit cursus pellentesque enim"
    clientname2 = "Manoj"
    clientdesignation2 = "CEO of Twitter"
    clientcompany2 = "Twitter"
    clienttext2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cursus nibh mauris, nec turpis orci lectus maecenas. Suspendisse sed magna eget nibh in turpis. Consequat duis diam lacus arcu. Faucibus venenatis felis id augue sit cursus pellentesque enim"
    clientname3 = "Manoj"
    clientdesignation3 = "CEO of Amazon"
    clientcompany3 = "Amazon"
    clienttext3 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cursus nibh mauris, nec turpis orci lectus maecenas. Suspendisse sed magna eget nibh in turpis. Consequat duis diam lacus arcu. Faucibus venenatis felis id augue sit cursus pellentesque enim"
    contactheadline = "Any queries"
    contactsubheadline = "Response within 24 hours"
    conatctimage = r"C:\Users\HP\PycharmProjects\BUILDER-OSS2.0\TestFiles\Logo.svg"
    address = "ES naidu House Chittoor AP,india,517124"
    mail = "manoj.endluri@gmail.com"
    facebook = "https://www.facebook.com/Ursmanoj0456/"
    twitter = "https://in.linkedin.com/in/ursmanoj56"
    instagram = "https://www.instagram.com/ursmanoj0456/"




